# Generated by Django 4.1.2 on 2023-01-27 04:24

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to=notes.models.file_upload_path),
        ),
    ]
