# Generated by Django 4.1.2 on 2023-01-27 04:25

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=notes.models.file_upload_path),
        ),
    ]
