# Generated by Django 4.1.2 on 2023-02-04 20:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uploaded_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
