# Generated by Django 4.1.2 on 2023-02-08 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_label_note_note_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('name', 'name')},
        ),
    ]
