# Generated by Django 4.1.2 on 2023-02-08 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_label_created_by_alter_label_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('name', 'created_by')},
        ),
    ]
