# Generated by Django 4.1.2 on 2023-02-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_label_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_label',
        ),
        migrations.AddField(
            model_name='note',
            name='note_label',
            field=models.ManyToManyField(blank=True, related_name='notes', to='notes.label'),
        ),
    ]
